# Generated by Django 4.0.3 on 2022-04-19 19:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycmu', '0011_alter_message_creation_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='creation_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 19, 19, 2, 0, 750417)),
        ),
    ]
