# Generated by Django 4.0.3 on 2022-04-19 19:34

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mycmu', '0012_alter_message_creation_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user_name',
        ),
        migrations.AlterField(
            model_name='careercomment',
            name='career_comment_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='career_comment_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='careercomment',
            name='career_post_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_id', to='mycmu.careerpost'),
        ),
        migrations.AlterField(
            model_name='careerpost',
            name='career_post_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='career_post_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='coursecomment',
            name='course_comment_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_comment_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='coursecomment',
            name='course_post_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_post_id', to='mycmu.coursepost'),
        ),
        migrations.AlterField(
            model_name='coursepost',
            name='course_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_id', to='mycmu.course'),
        ),
        migrations.AlterField(
            model_name='coursepost',
            name='course_post_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_post_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='message',
            name='creation_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 19, 19, 34, 10, 613130)),
        ),
        migrations.AlterField(
            model_name='message',
            name='from_user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_user_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='message',
            name='to_user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_user_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_creators', to=settings.AUTH_USER_MODEL),
        ),
    ]
