# Generated by Django 4.0.3 on 2022-04-20 18:39

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mycmu', '0014_alter_message_creation_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='careerpost',
            name='update_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coursepost',
            name='update_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='message',
            name='creation_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 20, 18, 38, 39, 525303)),
        ),
    ]
