# Generated by Django 4.0.3 on 2022-04-20 18:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycmu', '0015_careerpost_update_time_coursepost_update_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='creation_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 20, 18, 56, 51, 448719)),
        ),
    ]
